apiVersion: v1
kind: Service
metadata:
  name: flask-video-server
  labels:
    app: flask-video-server
spec:
  ports:
  - port: 50053
    protocol: TCP
  type: NodePort
  selector:
    app: flask-video-server

