apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-client
  name: flask-client
spec:
  selector:
    app: flask-client
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP


