apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-analytics
  name: flask-analytics
spec:
  selector:
    app: flask-analytics
  type: NodePort
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP

