apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-client
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 10
  template:
    metadata:
      labels:
        app: flask-client
    spec:
      containers:
      - name: flask-client
        image: thisdevydev32/ddm-flask-frontend-client:latest
        ports:
        - containerPort: 8080


